[features]
seeds = false
[programs.devnet]
solana_nft_demo = "9px1erHuqV9jHAAncku7omwMHNR7YkvugHET2tJa6MF8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
