[features]
seeds = false
[programs.devnet]
solana_nft_demo = "8WK7ZXXsqbx5j1We5pE6DYczTfE2vzu5qoQd2rb1sfUK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
